### ISSUE TITLE
Dissidia Final Fantasy NT Mesh problems

### ISSUE THREAD

**Issue by Andree12** [Joschuka/fmt_g1m#7]
![image](https://user-images.githubusercontent.com/49048262/74265424-29ff7880-4cc8-11ea-8dbf-588ca5b71bea.png)

[Dissidia NT PC Files.zip](https://github.com/Joschuka/fmt_g1m/files/4187417/Dissidia.NT.PC.Files.zip)

**Comment by neptuwunium** [comment]
Are these ripped from game memory or extracted from game archives?

**Comment by Joschuka** [comment]
This is the mesh with the problem 
![image](https://user-images.githubusercontent.com/43338144/74277754-5e9b2080-4d18-11ea-9f3e-8c3de3f211bf.png)

However as you can see at the very beginning of the video it's simulated by the physics engine. 
https://www.youtube.com/watch?v=p4VO-S9ods8

Cloth meshes have dummy weights and bone indices, probably used in some way by the physics engine I guess but they don't work with animations. That's why you see some weird deformation. 
This only thing I can do is to zero out these like I do for Cloth type 1 meshes (the ones with the drivers). However for some games the weights actually mean something and are linked to the armature (like in  your previous issue with Link) so I can't do that.

You'll have to export as it is and remove the weights from the mesh in your 3D software, then do something about it (physics simulation in the 3D software, adding bones or something), I can't fix this since it's supposed to be simulated at runtime.

**Comment by Joschuka** [comment]
Did more research and I was partly wrong, there are bones for these parts, try 1c5a3ec 
I don't expect these parts to be animated by the G2A file since they're probably physics driven but they shouldn't look completely deformed anymore when previewing in Noesis

**Comment by Joschuka** [comment]
Tried it myself today, I can confirm that it works as intented now.
